
## MODEL SELECTION AND METRICS

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv("ObesityDataset1.csv")
print(df)

      gender  age    height      weight family_history_with_overweight  \
0     Female   21  1.620000   64.000000                            yes
1     Female   21  1.520000   56.000000                            yes
2       Male   23  1.800000   77.000000                            yes
3       Male   27  1.800000   87.000000                             no
4       Male   22  1.780000   89.800000                             no
...      ...  ...       ...         ...                            ...
2106  Female   21  1.710730  131.408528                            yes
2107  Female   22  1.748584  133.742943                            yes
2108  Female   23  1.752206  133.689352                            yes
2109  Female   24  1.739450  133.346641                            yes
2110  Female   24  1.738836  133.472641                            yes

     caloric_food  vegetables  number_meals  food_between_meals smoke  water  \
0              no           2             3                   2    no      2
1              no           3             3                   2   yes      3
2              no           2             3                   2    no      2
3              no           3             3                   2    no      2
4              no           2             1                   2    no      2
...           ...         ...           ...                 ...   ...    ...
2106          yes           3             3                   2    no      2
2107          yes           3             3                   2    no      2
2108          yes           3             3                   2    no      2
2109          yes           3             3                   2    no      3
2110          yes           3             3                   2    no      3

     calories  activity  technology  alcohol         transportation  \
0          no         0           1        1  public_transportation
1         yes         3           0        2  public_transportation
2          no         2           1        3  public_transportation
3          no         2           0        3                walking
4          no         0           0        2  public_transportation
...       ...       ...         ...      ...                    ...
2106       no         2           1        2  public_transportation
2107       no         1           1        2  public_transportation
2108       no         1           1        2  public_transportation
2109       no         1           1        2  public_transportation
2110       no         1           1        2  public_transportation

      obesity_level
0                 2
1                 2
2                 2
3                 3
4                 4
...             ...
2106              7
2107              7
2108              7
2109              7
2110              7

[2111 rows x 17 columns]

In [49]:

from sklearn import preprocessing

#Label Encoding
LE= preprocessing.LabelEncoder()

# Fitting it to our dataset
df.gender = LE.fit_transform(df.gender)
df.family_history_with_overweight = LE.fit_transform(df.family_history_with_overweight)
df.caloric_food = LE.fit_transform(df.caloric_food)
df.smoke = LE.fit_transform(df.smoke)
df.calories = LE.fit_transform(df.calories)
df.transportation = LE.fit_transform(df.transportation)
df.head()

,gender,age,height,weight,family_history_with_overweight,caloric_food,vegetables,number_meals,food_between_meals,smoke,water,calories,activity,technology,alcohol,transportation,obesity_level
0,0,21,1.62,64.0,1,0,2,3,2,0,2,0,0,1,1,3,2
1,0,21,1.52,56.0,1,0,3,3,2,1,3,1,3,0,2,3,2
2,1,23,1.80,77.0,1,0,2,3,2,0,2,0,2,1,3,3,2
3,1,27,1.80,87.0,0,0,3,3,2,0,2,0,2,0,3,4,3
4,1,22,1.78,89.8,0,0,2,1,2,0,2,0,0,0,2,3,4

In [50]:
df.dtypes

gender                              int32
age                                 int64
height                            float64
weight                            float64
family_history_with_overweight      int32
caloric_food                        int32
vegetables                          int64
number_meals                        int64
food_between_meals                  int64
smoke                               int32
water                               int64
calories                            int32
activity                            int64
technology                          int64
alcohol                             int64
transportation                      int32
obesity_level                       int64
dtype: object

In [53]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,export_text

In [54]:
x=df.drop('obesity_level',axis=1)
y=df['obesity_level']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [55]:
x_train.head()

,gender,age,height,weight,family_history_with_overweight,caloric_food,vegetables,number_meals,food_between_meals,smoke,water,calories,activity,technology,alcohol,transportation
626,1,17,1.811238,58.830710,1,1,2,4,2,0,2,0,2,1,1,0
302,1,16,1.840000,45.000000,1,1,3,3,4,0,3,0,3,2,2,4
766,1,21,1.752391,79.109637,1,1,3,1,2,0,2,0,3,0,2,0
730,1,18,1.829142,59.933015,1,1,3,4,2,0,2,0,2,0,1,0
1205,0,34,1.679299,77.355417,1,1,3,2,2,0,2,0,1,1,1,0

# decusion tree classifier

In [75]:
model=DecisionTreeClassifier(random_state=0,max_depth=3)
s=model.fit(x_train,y_train)
s1=export_text(s)
print(s1)
pred=model.predict(x_test)
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

|--- feature_3 <= 99.91
|   |--- feature_3 <= 61.51
|   |   |--- feature_2 <= 1.66
|   |   |   |--- class: 2
|   |   |--- feature_2 >  1.66
|   |   |   |--- class: 1
|   |--- feature_3 >  61.51
|   |   |--- feature_3 <= 76.06
|   |   |   |--- class: 3
|   |   |--- feature_3 >  76.06
|   |   |   |--- class: 5
|--- feature_3 >  99.91
|   |--- feature_0 <= 0.50
|   |   |--- feature_13 <= 1.50
|   |   |   |--- class: 7
|   |   |--- feature_13 >  1.50
|   |   |   |--- class: 6
|   |--- feature_0 >  0.50
|   |   |--- feature_1 <= 22.50
|   |   |   |--- class: 5
|   |   |--- feature_1 >  22.50
|   |   |   |--- class: 6

              precision    recall  f1-score   support

           1       0.85      0.69      0.76        77
           2       0.50      0.37      0.42        79
           3       0.48      0.55      0.51        87
           4       0.00      0.00      0.00        92
           5       0.43      0.88      0.58       104
           6       0.86      0.92      0.89        95
           7       1.00      1.00      1.00       100

    accuracy                           0.64       634
   macro avg       0.59      0.63      0.59       634
weighted avg       0.59      0.64      0.60       634

[[ 53  23   1   0   0   0   0]
 [  9  29  38   0   3   0   0]
 [  0   5  48   0  34   0   0]
 [  0   1  13   0  76   2   0]
 [  0   0   1   0  91  12   0]
 [  0   0   0   0   8  87   0]
 [  0   0   0   0   0   0 100]]

C:\Users\VAISHNAVI\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [76]:
from sklearn.metrics import accuracy_score
print("Accuracy: ",accuracy_score(y_test,pred)*100)

Accuracy:  64.35331230283911

# randomforest classifier

In [74]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier(class_weight='balanced',random_state=1,max_depth=5,\
                               n_estimators=10,max_features=1)
model_rf.fit(x_train,y_train)
pred=model_rf.predict(x_test)
print("accuracy:",accuracy_score(y_test,pred)*100)
print(classification_report(y_test,pred))

accuracy: 63.40694006309149
              precision    recall  f1-score   support

           1       0.76      0.90      0.82        77
           2       0.57      0.44      0.50        79
           3       0.66      0.38      0.48        87
           4       0.65      0.40      0.50        92
           5       0.74      0.33      0.45       104
           6       0.53      0.99      0.69        95
           7       0.66      1.00      0.79       100

    accuracy                           0.63       634
   macro avg       0.65      0.63      0.61       634
weighted avg       0.65      0.63      0.60       634

In [77]:
from sklearn.metrics import accuracy_score
print("accuracy:",accuracy_score(y_test,pred)*100)

accuracy: 64.35331230283911

# adaboost classifier

In [78]:
from sklearn.ensemble import AdaBoostClassifier
model_ada=AdaBoostClassifier(learning_rate=0.01)
model_ada.fit(x_train,y_train)
pred=model_ada.predict(x_test)
print("accuracy:",accuracy_score(y_test,pred)*100)
print(classification_report(y_test,pred))

accuracy: 30.126182965299687
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        77
           2       0.33      0.52      0.40        79
           3       0.48      0.54      0.51        87
           4       0.00      0.00      0.00        92
           5       0.25      0.99      0.40       104
           6       0.00      0.00      0.00        95
           7       0.00      0.00      0.00       100

    accuracy                           0.30       634
   macro avg       0.15      0.29      0.19       634
weighted avg       0.15      0.30      0.19       634

C:\Users\VAISHNAVI\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))